#ifndef LANG_H
#define LANG_H

// Sélection de la langue (décommentez la ligne correspondante)
#define LANG_EN  // Pour l'anglais
//#define LANG_FR  // Pour le français
//#define LANG_RU  // Pour le russe
//#define LANG_IT  // Pour l'italien

#ifdef LANG_EN
    #define TXT_OVERHEAT "ERROR: Overheat"
    #define TXT_THERMISTOR "ERROR: Thermistor"
    #define TXT_GEAR_RATIO "Gear ratio: "
    #define TXT_SPEED "Speed:   mm/s"
    #define TXT_MAIN_SCREEN "Redrawing main screen..."
    #define TXT_WARNINGS "*!WARNINGS!*"
    #define TXT_EMERGENCY_TRIGGERED "   Emergency stop triggered."
    #define TXT_PRESS_TO_RESTART "   Press encoder to restart."
    #define TXT_BUTTON_HELD "   Button held for 4 seconds."
    #define TXT_ASTERISK "*"
    #define TXT_DASH "-"
    #define TXT_C "C"
    #define TXT_ENC "ENC:"
    #define TXT_END "END"
    #define TXT_ERR "ERR"
    #define TXT_EXTRA "Extra:    mm'"
    #define TXT_O "O"
    #define TXT_OFF "OFF"
    #define TXT_OK "OK "
    #define TXT_ON "ON "
    #define TXT_PID "PID:"
    #define TXT_PROGRESS "Progress:  m'"
    #define TXT_SENS_H "Sens/H:"
    #define TXT_STEP_S "Step/s:"
    #define TXT_T "T:"
    #define TXT_X "X"
    #define TXT_SMALL_X "x"

#elif defined(LANG_FR)
    #define TXT_OVERHEAT "ERREUR: Surchauffe"
    #define TXT_THERMISTOR "ERREUR: Thermistance"
    #define TXT_GEAR_RATIO "Ratio d'engrenage: "
    #define TXT_SPEED "Vitesse: mm/s"
    #define TXT_MAIN_SCREEN "Redessiner l'écran principal..."
    #define TXT_WARNINGS "*!AVERTISSEMENTS!*"
    #define TXT_EMERGENCY_TRIGGERED "  Arret d'urgence declenche."
    #define TXT_PRESS_TO_RESTART " Press bouton pour redemarrer."
    #define TXT_BUTTON_HELD "Bouton maintenu pendant 4 sec.."
    #define TXT_ASTERISK "*"
    #define TXT_DASH "-"
    #define TXT_C "C"
    #define TXT_ENC "ENC:"
    #define TXT_END "END"
    #define TXT_ERR "ERR"
    #define TXT_EXTRA "Extra:    mm'"
    #define TXT_O "O"
    #define TXT_OFF "OFF"
    #define TXT_OK "OK "
    #define TXT_ON "ON "
    #define TXT_PID "PID:"
    #define TXT_PROGRESS "Progression: m'"
    #define TXT_SENS_H "Sens/H:"
    #define TXT_STEP_S "Step/s:"
    #define TXT_T "T:"
    #define TXT_X "X"
    #define TXT_SMALL_X "x"

#elif defined(LANG_RU)
    #define TXT_OVERHEAT "ОШИБКА: Перегрев"
    #define TXT_THERMISTOR "ОШИБКА: Терморезистор"
    #define TXT_GEAR_RATIO "Передаточное отношение: "
    #define TXT_SPEED "Скорость:   мм/с"
    #define TXT_MAIN_SCREEN "Перерисовка главного экрана..."
    #define TXT_WARNINGS "*!ПРЕДУПРЕЖДЕНИЯ!*"
    #define TXT_EMERGENCY_TRIGGERED "Сработала аварийная остановка."
    #define TXT_PRESS_TO_RESTART "Нажмите энкодер для перезапуска."
    #define TXT_BUTTON_HELD "Кнопка удерживается 4 секунды."
    #define TXT_ASTERISK "*"
    #define TXT_DASH "-"
    #define TXT_C "C"
    #define TXT_ENC "ENC:"
    #define TXT_END "END"
    #define TXT_ERR "ERR"
    #define TXT_EXTRA "Дополнительно: м'"
    #define TXT_O "O"
    #define TXT_OFF "ВЫКЛ"
    #define TXT_OK "ОК "
    #define TXT_ON "ВКЛ "
    #define TXT_PID "PID:"
    #define TXT_PROGRESS "Прогресс:  м'"
    #define TXT_SENS_H "Сенс/ч:"
    #define TXT_STEP_S "Шаг/с:"
    #define TXT_T "T:"
    #define TXT_X "X"
    #define TXT_SMALL_X "x"

#elif defined(LANG_IT)
    #define TXT_OVERHEAT "ERRORE: Surriscaldamento"
    #define TXT_THERMISTOR "ERRORE: Termistore"
    #define TXT_GEAR_RATIO "Rapporto di trasmissione: "
    #define TXT_SPEED "Velocità:   mm/s"
    #define TXT_MAIN_SCREEN "Ridisegno dello schermo principale..."
    #define TXT_WARNINGS "*!AVVISI!*"
    #define TXT_EMERGENCY_TRIGGERED "Arresto di emergenza attivato."
    #define TXT_PRESS_TO_RESTART "Premi l'encoder per riavviare."
    #define TXT_BUTTON_HELD "Pulsante tenuto premuto per 4 secondi."
    #define TXT_ASTERISK "*"
    #define TXT_DASH "-"
    #define TXT_C "C"
    #define TXT_ENC "ENC:"
    #define TXT_END "END"
    #define TXT_ERR "ERR"
    #define TXT_EXTRA "Extra: mm'"
    #define TXT_O "O"
    #define TXT_OFF "OFF"
    #define TXT_OK "OK "
    #define TXT_ON "ON "
    #define TXT_PID "PID:"
    #define TXT_PROGRESS "Avanzamento: m'"
    #define TXT_SENS_H "Sens/H:"
    #define TXT_STEP_S "Passo/i:"
    #define TXT_T "T:"
    #define TXT_X "X"
    #define TXT_SMALL_X "x"
#endif

#endif // LANG_H
